### ISSUE TITLE
[Data] ImageRead: No OperationDescriptor

### ISSUE THREAD

**Issue by fb71** [Polymap4/polymap4-core#110]
[INFO]  BatikProgressProvider  : [PROGRESS] Connect layer "elevation.tif.3857" - done. (false)
[WARN]  LayerStyleDashlet      : 
java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: ImageRead: No OperationDescriptor is registered in the current operation registry under this name.
	at org.polymap.p4.layer.RasterLayer.lambda$2(RasterLayer.java:90)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
	at org.polymap.p4.layer.RasterLayer.lambda$0(RasterLayer.java:84)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	at org.polymap.core.runtime.JobExecutor$2.runWithException(JobExecutor.java:103)
	at org.polymap.core.runtime.UIJob.lambda$0(UIJob.java:232)
	at org.eclipse.rap.rwt.internal.lifecycle.ContextUtil.runNonUIThreadWithFakeContext(ContextUtil.java:67)
	at org.eclipse.rap.rwt.internal.lifecycle.ContextUtil.runNonUIThreadWithFakeContext(ContextUtil.java:41)
	at org.eclipse.rap.rwt.lifecycle.UICallBack.runNonUIThreadWithFakeContext(UICallBack.java:54)
	at org.polymap.core.runtime.session.RapSessionContextProvider$RapSessionContext.execute(RapSessionContextProvider.java:132)
	at org.polymap.core.runtime.UIJob.run(UIJob.java:228)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
Caused by: java.lang.IllegalArgumentException: ImageRead: No OperationDescriptor is registered in the current operation registry under this name.
	at javax.media.jai.JAI.createNS(JAI.java:1070)
	at javax.media.jai.JAI.create(JAI.java:973)
	at org.geotools.gce.geotiff.GeoTiffReader.read(GeoTiffReader.java:654)
	at org.geotools.coverage.grid.io.AbstractGridCoverage2DReader.read(AbstractGridCoverage2DReader.java:261)
	at org.polymap.p4.layer.RasterLayer.doConnectLayer(RasterLayer.java:135)
	at org.polymap.p4.layer.RasterLayer.lambda$2(RasterLayer.java:87)
	... 11 more

**Comment by fb71** [comment]
- http://osgeo-org.1560.x6.nabble.com/Loading-EPSG-4326-CRS-td5074897.html
  - https://stackoverflow.com/questions/7051603/jai-vendorname-null/18495658
  - http://forum.servoy.com/viewtopic.php?f=8&t=13625&p=70765#p70765
