### ISSUE TITLE
[Data.RS] Exceptions if geometries are missing

### ISSUE THREAD

**Issue by stundzig** [Polymap4/polymap4-core#87]
During imports of CSV or Excel its possible that geometries are completely missing.

Since commit https://github.com/Polymap4/polymap4-core/commit/27f3a33c3924cb5fd904cd209ff5c922c8dc0247 this is broken.

```
org.eclipse.core.commands.ExecutionException: java.lang.NullPointerException
    at org.polymap.core.operation.DefaultOperation.handleException(DefaultOperation.java:61)
    at org.polymap.core.operation.DefaultOperation.execute(DefaultOperation.java:67)
    at org.polymap.core.operation.LogOperationConcernFactory$1.execute(LogOperationConcernFactory.java:46)
    at org.polymap.p4.data.importer.features.AddLayerForImportedFeaturesConcern$AddLayerOperationConcern.execute(AddLayerForImportedFeaturesConcern.java:97)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at org.polymap.core.operation.OperationExecutor.invoke(OperationExecutor.java:113)
    at com.sun.proxy.$Proxy39.execute(Unknown Source)
    at org.eclipse.core.commands.operations.DefaultOperationHistory.execute(DefaultOperationHistory.java:513)
    at org.polymap.core.operation.OperationSupport$5.run(OperationSupport.java:271)
    at org.polymap.core.operation.OperationSupport$OperationJob.runWithException(OperationSupport.java:340)
    at org.polymap.core.runtime.UIJob.lambda$1(UIJob.java:194)
    at org.polymap.core.runtime.UIJob$$Lambda$93/1068644260.run(Unknown Source)
    at org.eclipse.rap.rwt.internal.lifecycle.ContextUtil.runNonUIThreadWithFakeContext(ContextUtil.java:67)
    at org.eclipse.rap.rwt.internal.lifecycle.ContextUtil.runNonUIThreadWithFakeContext(ContextUtil.java:41)
    at org.eclipse.rap.rwt.lifecycle.UICallBack.runNonUIThreadWithFakeContext(UICallBack.java:54)
    at org.polymap.core.runtime.session.RapSessionContextProvider$RapSessionContext.execute(RapSessionContextProvider.java:132)
    at org.polymap.core.runtime.UIJob.run(UIJob.java:190)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
Caused by: java.lang.RuntimeException: java.lang.NullPointerException
    at org.polymap.core.data.rs.RFeatureStore.addFeatures(RFeatureStore.java:293)
    at org.polymap.p4.data.importer.features.ImportFeaturesOperation.doExecute(ImportFeaturesOperation.java:99)
    at org.polymap.core.operation.DefaultOperation.lambda$0(DefaultOperation.java:67)
    at org.polymap.core.operation.DefaultOperation$$Lambda$294/1737857406.call(Unknown Source)
    at org.polymap.core.operation.DefaultOperation.handleException(DefaultOperation.java:55)
    ... 20 more
Caused by: java.lang.NullPointerException
    at org.polymap.core.data.rs.RFeatureStore$2.visit(RFeatureStore.java:267)
    at org.geotools.data.DataUtilities.visit(DataUtilities.java:2867)
    at org.geotools.feature.collection.AbstractFeatureCollection.accepts(AbstractFeatureCollection.java:226)
    at org.polymap.core.data.rs.RFeatureStore.addFeatures(RFeatureStore.java:249)
```

I could make a workaround with 

```
// sanity check: geom
if (schema.getGeometryDescriptor() != null
       && feature.getDefaultGeometryProperty().getValue() == null 
       && !schema.getGeometryDescriptor().isNillable()) {
```

but then getBounds() throws an exception:

```
[ERROR] LogAdapter             : Die Aktion "New layer" hat ein Problem festgestellt und musste erfolglos abgebrochen werden.
org.eclipse.core.commands.ExecutionException: java.io.IOException: java.lang.NullPointerException
    at org.polymap.core.operation.DefaultOperation.handleException(DefaultOperation.java:61)
    at org.polymap.core.operation.DefaultOperation.execute(DefaultOperation.java:67)
    at org.polymap.core.operation.LogOperationConcernFactory$1.execute(LogOperationConcernFactory.java:46)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at org.polymap.core.operation.OperationExecutor.invoke(OperationExecutor.java:113)
    at com.sun.proxy.$Proxy40.execute(Unknown Source)
    at org.eclipse.core.commands.operations.DefaultOperationHistory.execute(DefaultOperationHistory.java:513)
    at org.polymap.core.operation.OperationSupport$5.run(OperationSupport.java:271)
    at org.polymap.core.operation.OperationSupport$OperationJob.runWithException(OperationSupport.java:340)
    at org.polymap.core.runtime.UIJob.lambda$1(UIJob.java:194)
    at org.polymap.core.runtime.UIJob$$Lambda$94/677809402.run(Unknown Source)
    at org.eclipse.rap.rwt.internal.lifecycle.ContextUtil.runNonUIThreadWithFakeContext(ContextUtil.java:67)
    at org.eclipse.rap.rwt.internal.lifecycle.ContextUtil.runNonUIThreadWithFakeContext(ContextUtil.java:41)
    at org.eclipse.rap.rwt.lifecycle.UICallBack.runNonUIThreadWithFakeContext(UICallBack.java:54)
    at org.polymap.core.runtime.session.RapSessionContextProvider$RapSessionContext.execute(RapSessionContextProvider.java:132)
    at org.polymap.core.runtime.UIJob.run(UIJob.java:190)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
Caused by: java.lang.RuntimeException: java.io.IOException: java.lang.NullPointerException
    at org.polymap.core.data.rs.RFeatureStore$1.getBounds(RFeatureStore.java:130)
    at org.polymap.core.catalog.resolve.DefaultResourceInfo.getBounds(DefaultResourceInfo.java:67)
    at org.polymap.p4.layer.NewLayerOperation.adaptMapBBox(NewLayerOperation.java:151)
    at org.polymap.p4.layer.NewLayerOperation.doWithCommit(NewLayerOperation.java:132)
    at org.polymap.core.project.ops.TwoPhaseCommitOperation.doExecute(TwoPhaseCommitOperation.java:78)
    at org.polymap.core.operation.DefaultOperation.lambda$0(DefaultOperation.java:67)
    at org.polymap.core.operation.DefaultOperation$$Lambda$330/670949056.call(Unknown Source)
    at org.polymap.core.operation.DefaultOperation.handleException(DefaultOperation.java:55)
    ... 19 more
Caused by: java.io.IOException: java.lang.NullPointerException
    at org.polymap.core.data.rs.lucene.LuceneQueryDialect.getBounds(LuceneQueryDialect.java:197)
    at org.polymap.core.data.rs.RFeatureStore.getBounds(RFeatureStore.java:194)
    at org.polymap.core.data.rs.RFeatureStore.getBounds(RFeatureStore.java:189)
    at org.polymap.core.data.rs.RFeatureStore$1.getBounds(RFeatureStore.java:127)
    ... 26 more
Caused by: java.lang.NullPointerException
    at org.polymap.core.data.rs.lucene.LuceneQueryDialect.getBounds(LuceneQueryDialect.java:169)
```

**Comment by fb71** [comment]
It's not broken, this change was completely intentional. If the schema has a geometry property, then all features have to have geometries. Otherwise all kind of stupid behaviour is going on. For example: what is the bounding box of a not exting geometry?

All importers have to check this.

If an importer wants to create features without geometry by intention, then it has to create a schema without geometry property.

**Comment by stundzig** [comment]
I've removed the geometrydescriptor, if the CSV doesnt contain any coordinates. But now i got an exception during getBounds()

```
Caused by: java.lang.NullPointerException
    at org.polymap.core.data.rs.lucene.LuceneQueryDialect.getBounds(LuceneQueryDialect.java:152)
    at org.polymap.core.data.rs.RFeatureStore.getBounds(RFeatureStore.java:194)
    at org.polymap.core.data.rs.RFeatureStore.getBounds(RFeatureStore.java:189)
    at org.polymap.core.data.rs.RFeatureStore$1.getBounds(RFeatureStore.java:127)
    at org.polymap.core.catalog.resolve.DefaultResourceInfo.getBounds(DefaultResourceInfo.java:67)
    at org.polymap.p4.layer.NewLayerOperation.adaptMapBBox(NewLayerOperation.java:151)
    at org.polymap.p4.layer.NewLayerOperation.doWithCommit(NewLayerOperation.java:132)
    at org.polymap.core.project.ops.TwoPhaseCommitOperation.doExecute(TwoPhaseCommitOperation.java:78)
    at org.polymap.core.operation.DefaultOperation.lambda$0(DefaultOperation.java:67)
    at org.polymap.core.operation.DefaultOperation$$Lambda$292/173472450.call(Unknown Source)
    at org.polymap.core.operation.DefaultOperation.handleException(DefaultOperation.java:55)
```

**Comment by stundzig** [comment]
The initial zoom of the mapviewer should also prevented.

**Comment by fb71** [comment]
The new code in NewLayerOperation breaks adding external resources.

**Comment by fb71** [comment]
FeatureLayer is the API to get the FeatureSource of an ILayer.
