### ISSUE TITLE
[Geoserver] Layers with . breaking the RequestReader

### ISSUE THREAD

**Issue by stundzig** [Polymap4/polymap4-core#89]
```
[INFO]  ServiceContext2        : SessionContext: DefaultSessionContext[sessionKey=GeoServer:/ows-32643887, attributes={org.polymap.p4.project.ProjectRepository$SessionHolder=org.polymap.p4.project.ProjectRepository$SessionHolder@1378041, org.polymap.core.security.SecurityContext=org.polymap.core.security.SecurityContext@178df8}]
Sep 26, 2016 10:37:28 AM org.geoserver.ows.util.RequestObjectLogger invoke
INFO: 
Request: getServiceInfo
Sep 26, 2016 10:37:28 AM org.geoserver.ows.Dispatcher exception
SEVERE: 
org.geoserver.platform.ServiceException: Could not find layer webatlasde.light
    at org.geoserver.wms.map.GetMapKvpRequestReader.parseLayers(GetMapKvpRequestReader.java:1325)
    at org.geoserver.wms.map.GetMapKvpRequestReader.read(GetMapKvpRequestReader.java:231)
    at org.polymap.service.geoserver.spring.BBoxGetMapKvpRequestReader.read(BBoxGetMapKvpRequestReader.java:47)
    at org.geoserver.wms.map.GetMapKvpRequestReader.read(GetMapKvpRequestReader.java:84)
    at org.geoserver.ows.Dispatcher.parseRequestKVP(Dispatcher.java:1489)
    at org.geoserver.ows.Dispatcher.dispatch(Dispatcher.java:677)
    at org.geoserver.ows.Dispatcher.handleRequestInternal(Dispatcher.java:265)
```

**Comment by stundzig** [comment]
And also with space and german umlauts like ß.

```
org.geoserver.platform.ServiceException: Could not find layer Straßenbaumkataster Leipzig
    at org.geoserver.wms.map.GetMapKvpRequestReader.parseLayers(GetMapKvpRequestReader.java:1325)
    at org.geoserver.wms.map.GetMapKvpRequestReader.read(GetMapKvpRequestReader.java:231)
```
