### ISSUE TITLE
[Style] GeoServer startup

### ISSUE THREAD

**Issue by fb71** [Polymap4/polymap4-core#92]
Caused by: java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at org.geotools.xml.impl.NodeImpl.getChildValue(NodeImpl.java:351)
	at org.geotools.filter.v1_0.OGCPropertyIsLessThanOrEqualToBinding.parse(OGCPropertyIsLessThanOrEqualToBinding.java:84)
	at org.geotools.xml.impl.ParseExecutor.visit(ParseExecutor.java:156)
	... 66 more
java.lang.RuntimeException: java.lang.ClassCastException: org.geotools.xml.impl.DocumentHandlerImpl cannot be cast to org.geotools.xml.impl.ElementHandler : FilterMappedColors
	at org.polymap.core.style.serialize.sld.StylePropertyValueHandler.handle(StylePropertyValueHandler.java:101)
	at org.polymap.core.style.serialize.sld.StyleCompositeSerializer.setValue(StyleCompositeSerializer.java:98)
	at org.polymap.core.style.serialize.sld.FillSerializer.doSerialize(FillSerializer.java:47)
	at org.polymap.core.style.serialize.sld.FillSerializer.doSerialize(FillSerializer.java:1)
	at org.polymap.core.style.serialize.sld.StyleCompositeSerializer.serialize(StyleCompositeSerializer.java:61)
	at org.polymap.core.style.serialize.sld.PolygonStyleSerializer.doSerializeStyle(PolygonStyleSerializer.java:47)
	at org.polymap.core.style.serialize.sld.PolygonStyleSerializer.doSerializeStyle(PolygonStyleSerializer.java:1)
	at org.polymap.core.style.serialize.sld.StyleSerializer.doSerialize(StyleSerializer.java:115)
	at org.polymap.core.style.serialize.sld.StyleSerializer.doSerialize(StyleSerializer.java:1)
	at org.polymap.core.style.serialize.sld.StyleCompositeSerializer.serialize(StyleCompositeSerializer.java:61)
	at org.polymap.core.style.serialize.sld.SLDSerializer.serializeStyle(SLDSerializer.java:161)
	at org.polymap.core.style.serialize.sld.SLDSerializer.buildStyle(SLDSerializer.java:116)
	at org.polymap.core.style.serialize.sld.SLDSerializer.serialize(SLDSerializer.java:102)
	at org.polymap.core.style.model.StyleRepository.lambda$0(StyleRepository.java:184)
	at org.polymap.core.runtime.cache.Soft2Cache$Loader.apply(Soft2Cache.java:118)
	at org.polymap.core.runtime.cache.Soft2Cache$Loader.apply(Soft2Cache.java:1)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
	at org.polymap.core.runtime.cache.Soft2Cache.get(Soft2Cache.java:143)
	at org.polymap.core.style.model.StyleRepository.serializedFeatureStyle(StyleRepository.java:176)
	at org.polymap.core.style.model.StyleRepository.serializedFeatureStyle(StyleRepository.java:157)
	at io.mapzone.arena.GeoServerStarter$1.lambda$1(GeoServerStarter.java:151)
	at org.polymap.core.data.feature.FeatureRenderProcessor2.getMapRequest(FeatureRenderProcessor2.java:136)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.polymap.core.data.pipeline.ProcessorSignature.invoke(ProcessorSignature.java:156)
	at org.polymap.core.data.pipeline.DepthFirstStackExecutor.execute(DepthFirstStackExecutor.java:65)
	at org.polymap.service.geoserver.spring.PipelineMapOutputFormat$1.runWithException(PipelineMapOutputFormat.java:217)
	at org.polymap.core.runtime.UIJob.lambda$0(UIJob.java:199)
	at org.polymap.core.runtime.session.DefaultSessionContext$1.call(DefaultSessionContext.java:169)
	at org.polymap.core.runtime.session.DefaultSessionContext.execute(DefaultSessionContext.java:155)
	at org.polymap.core.runtime.session.DefaultSessionContext.execute(DefaultSessionContext.java:167)
	at org.polymap.core.runtime.UIJob.run(UIJob.java:195)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
Caused by: java.lang.RuntimeException: java.lang.ClassCastException: org.geotools.xml.impl.DocumentHandlerImpl cannot be cast to org.geotools.xml.impl.ElementHandler
	at org.polymap.core.style.model.FilterMappedValues.decode(FilterMappedValues.java:64)
	at org.polymap.core.style.model.FilterMappedValues.lambda$0(FilterMappedValues.java:55)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.polymap.core.style.model.FilterMappedValues.filters(FilterMappedValues.java:55)
	at org.polymap.core.style.serialize.sld.FilterMappedValuesHandler.doHandle(FilterMappedValuesHandler.java:55)
	at org.polymap.core.style.serialize.sld.StylePropertyValueHandler.handle(Styl

**Comment by fb71** [comment]
:)
