### ISSUE TITLE
Info click on feature broken

### ISSUE THREAD

**Issue by moovida** [Polymap4/polymap4-core#99]
When I have the attributes table open and click on an object on the map, the record is not selected any more and I get the following error in the console:

[INFO]  ProjectMapPanel        : event: {"feature":{"coordinate":[4180144.50050426,671046.879512552],"pixel":[481,199]}}
[INFO]  ProjectMapPanel        : Multiple features found: 19
[INFO]  ProjectMapPanel        : clicked: SimpleFeatureImpl:gpsimplenotes=[SimpleFeatureImpl.Attribute: the_geom<the_geom id=fid--30c17b7a_15a6feb989f_-4520>=POINT (37.5525 6.023953), SimpleFeatureImpl.Attribute: text<text id=fid--30c17b7a_15a6feb989f_-4520>=J51, SimpleFeatureImpl.Attribute: description<description id=fid--30c17b7a_15a6feb989f_-4520>= - , SimpleFeatureImpl.Attribute: ts<ts id=fid--30c17b7a_15a6feb989f_-4520>=2013-05-23 11:57:04, SimpleFeatureImpl.Attribute: altim<altim id=fid--30c17b7a_15a6feb989f_-4520>=1288.4000244140625, SimpleFeatureImpl.Attribute: isdirty<isdirty id=fid--30c17b7a_15a6feb989f_-4520>=1]
[INFO]  LazyFeatureContentPr...: Index from cache: 0
[WARN]  DisplayingListener     : Error during event dispatch: java.lang.IllegalStateException: Fid not found: fid--30c17b7a_15a6feb989f_-4520
java.lang.IllegalStateException: Fid not found: fid--30c17b7a_15a6feb989f_-4520
	at org.polymap.rhei.table.LazyFeatureContentProvider.indexOfFid(LazyFeatureContentProvider.java:212)
	at org.polymap.p4.layer.FeatureSelectionTable.onFeatureClick(FeatureSelectionTable.java:216)
	at sun.reflect.GeneratedMethodAccessor64.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.polymap.core.runtime.event.AnnotatedEventListener$AnnotatedMethod.handleEvent(AnnotatedEventListener.java:197)
	at org.polymap.core.runtime.event.DisplayingListener$1.run(DisplayingListener.java:58)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:38)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:180)
	at org.eclipse.swt.widgets.Display.runPendingMessages(Display.java:1196)
	at org.eclipse.swt.widgets.Display.safeReadAndDispatch(Display.java:1176)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:1168)
	at org.polymap.rhei.batik.BatikApplication.createUI(BatikApplication.java:163)
	at org.eclipse.rap.rwt.internal.lifecycle.RWTLifeCycle.createUI(RWTLifeCycle.java:172)
	at org.eclipse.rap.rwt.internal.lifecycle.RWTLifeCycle$UIThreadController.run(RWTLifeCycle.java:284)
	at java.lang.Thread.run(Thread.java:745)
	at org.eclipse.rap.rwt.internal.lifecycle.UIThread.run(UIThread.java:105)

**Comment by moovida** [comment]
This has been solved by the featurecache.
